<?php declare(strict_types=1);

namespace App\Entity;

use DateTimeImmutable;
use Sadl\Framework\Dbal\Entity;

class Post extends Entity
{
    /**
     * @param int|null $id
     * @param string $title
     * @param string $body
     * @param \DateTimeImmutable $dateCreatedAt
     */
    public function __construct(
        private ?int $id, // null because the id is generated by the database
        private string $title,
        private string $body,
        private DateTimeImmutable $dateCreatedAt,
    )
    {
    }

    /**
     * @param string $title
     * @param string $body
     * @param int|null $id
     * @param \DateTimeImmutable|null $dateCreatedAt
     *
     * @return \App\Entity\Post
     */
    public static function create(
        string $title,
        string $body,
        ?int $id = null,
        ?DateTimeImmutable $dateCreatedAt = null
    ): Post
    {
        return new self($id, $title, $body, $dateCreatedAt ?? new DateTimeImmutable());
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @param int|null $id
     */
    public function setId(?int $id): void
    {
        $this->id = $id;
    }

    /**
     * @return string
     */
    public function getTitle(): string
    {
        return $this->title;
    }

    /**
     * @param string $title
     */
    public function setTitle(string $title): void
    {
        $this->title = $title;
    }

    /**
     * @return string
     */
    public function getBody(): string
    {
        return $this->body;
    }

    /**
     * @param string $body
     */
    public function setBody(string $body): void
    {
        $this->body = $body;
    }

    /**
     * @return \DateTimeImmutable
     */
    public function getDateCreatedAt(): DateTimeImmutable
    {
        return $this->dateCreatedAt;
    }

    /**
     * @param \DateTimeImmutable $dateCreatedAt
     */
    public function setDateCreatedAt(DateTimeImmutable $dateCreatedAt): void
    {
        $this->dateCreatedAt = $dateCreatedAt;
    }
}